### ISSUE TITLE
 res.json is not a function

### ISSUE THREAD

**Issue by Geczy** [samuv/bee-plugin#10]
index.js:2673 Uncaught (in promise) TypeError: res.json is not a function

```
beeTest.getToken(clientId, clientSecret)
  .then((res) => res.json()) // return fetch promise
  .then((template) => beeTest.start(beeConfig, template))
```

**Comment by Geczy** [comment]
It already brings back a parsed JSON so that line can be removed to look like 

```
beeTest.getToken(clientId, clientSecret)
  .then((template) => beeTest.start(beeConfig, template))
```

**Comment by Geczy** [comment]
The above code generates a 400 bad request

The template isn't returned from anything so that whole code should look like this:

```

beeTest.getToken(clientId, clientSecret)
  .then(() => beeTest.start(beeConfig, template))

```

Now it's working.

**Comment by samuv** [comment]
Thanks, @Geczy, you are right the example is wrong.

I will update the example ASAP!

**Comment by samuv** [comment]
Fixed on master!
