### ISSUE TITLE
failed to complile

### ISSUE THREAD

**Issue by rcorzogutierrez** [samuv/bee-plugin#14]
when i tried start on windows,  it show me this error

![image](https://user-images.githubusercontent.com/5765375/28425787-52fd29c8-6d3f-11e7-8be9-aac35d03dae0.png)

**Comment by samuv** [comment]
Hi @rcorzogutierrez 
Sorry to hear that, try to this config in 'config/webpack.config.dev.js' and relaunch the start command.

`var path = require('path')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var paths = require('./paths')

module.exports = {
  entry: [
    require.resolve('whatwg-fetch'),
    require.resolve('./src/integration.js')
  ],
  devtool: 'cheap-module-source-map',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader?presets[]=env'
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.integrationHtml,
    }),
  ]
}`

**Comment by rcorzogutierrez** [comment]
Hi @samuv 
Sorry, the same problem remains.

**Comment by samuv** [comment]
Oh! I get it, it's missing the compiled part, just forget the new config and roll back on the version before then you can run 

> npm run build

 before the 

> npm start 

OR change the first line in 'src/integration.js'

```javascript
import Bee from './bee'
```

I will fix ASAP the repo

**Comment by samuv** [comment]
I have updated the repo https://github.com/samuv/bee-plugin/pull/15

Let me know if this fix the issue

**Comment by rcorzogutierrez** [comment]
Perfect!!!
![image](https://user-images.githubusercontent.com/5765375/28432467-04425f12-6d56-11e7-96cb-dbc72a59b16b.png)

**Comment by samuv** [comment]
Awesome!
