### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by benxgao** [samuv/bee-plugin#17]
I am trying to generate token on server side, but it always failed with error "fetch is not defined".

Will it be resolved if we explicitly import `fetch` when it is being used?

**Comment by samuv** [comment]
Hi @benxgao,

This is a wrapper for the client side, if you want to generate a token on the server side you need to call the endpoint for authentication, here some documentations:

Official Beefree docs https://help.beefree.io/hc/en-us/articles/202991192-Initializing-the-plugin
Nodejs example https://gist.github.com/andrei-tofan/aa8bd4910035d8fd8c780bb9db6f337b

You can also try to include in your project some polyfill on your side but I don't really know it can work: https://www.npmjs.com/package/universal-fetch

Let me know what you choose to use :)

**Comment by benxgao** [comment]
Tried `require('isomorphic-fetch');` in the file of generating token on server side, it works.

**Comment by samuv** [comment]
Nice! good to know.
