### ISSUE TITLE
BeeFree not show content, setting and rows

### ISSUE THREAD

**Issue by phucphanJaneto** [samuv/bee-plugin#18]
Hi @samuv 

I'm trying to integrate beefree into my angular 5 project through bee-plugin. But I get an unknow error. I don't see any content, setting or rows in right columns. 

![beefree](https://user-images.githubusercontent.com/37202364/41698345-093be5e2-7548-11e8-8ade-3418eb2280a7.PNG)

![beefree2](https://user-images.githubusercontent.com/37202364/41698346-097912dc-7548-11e8-93fe-a76dcc101f0e.PNG)

![beefree3](https://user-images.githubusercontent.com/37202364/41698348-0a1da1ee-7548-11e8-855e-39701a6eac31.PNG)

Please see this and let me know where I was wrong

**Comment by samuv** [comment]
Hi @phucphanJaneto 

You need to start with a valid template.

See the doc here:
https://github.com/samuv/bee-plugin#template-json 

Or see the example integration here:
https://github.com/samuv/bee-plugin/blob/master/src/integration.js

Let me know if resolve your issue

**Comment by phucphanJaneto** [comment]
@samuv : Many thanks. I'll close this taks
